### ISSUE TITLE
HTML Special chars

### ISSUE THREAD

**Issue by martoio** [roberb57/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/

https://github.com/roberb57/prj-rev-bwfs-dasmoto/blob/bbe86da4848c7987330086765672531b2f4ee72e/Dasmoto/index.html#L9

The ampersand should be written as:
``&amp;``

**Comment by roberb57** [comment]
Thanks I kind of guess something was wrong when it stayed red, but the code still worked.

**Comment by martoio** [comment]
Your browser will interpret the ``&`` as is, but it's good to know about the special character encoding. As an example, how would you put in a copyright symbol? (chances are you don't know the keyboard shortcut for this, but in HTML you can just do ``&copy;``
