### ISSUE TITLE
Repeating CSS

### ISSUE THREAD

**Issue by martoio** [roberb57/prj-rev-bwfs-dasmoto#3]
Notice how this part in the CSS repeats:
https://github.com/roberb57/prj-rev-bwfs-dasmoto/blob/bbe86da4848c7987330086765672531b2f4ee72e/Dasmoto/resources/css/style.css#L13-L15

Avoid duplicating code. Instead, you can do:
```
h2{
    font-size: 32px;
    color: white;
    font-weight: bold;
}
.brushes {
    background-color: mediumspringgreen;
}
.frames {
    background-color: lightcoral;
}
.paint {
    background-color: skyblue;
}
...
```

**Comment by roberb57** [comment]
Yep that looks a lot cleaner and less work
